# Generated by Django 5.0.7 on 2024-07-17 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('payment_due', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('payment_terms', models.IntegerField(choices=[(1, 'Net 1 Day'), (7, 'Net 7 Days'), (14, 'Net 14 Days'), (30, 'Net 30 Days')])),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('draft', 'Draft')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='invoice.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_invoices', to='invoice.address')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
        ),
    ]
