# Generated by Django 5.0.7 on 2024-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_address',
            new_name='clientAddress',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_email',
            new_name='clientEmail',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_name',
            new_name='clientName',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_due',
            new_name='paymentDue',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_terms',
            new_name='paymentTerms',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sender_address',
            new_name='senderAddress',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
