# Generated by Django 5.0.7 on 2024-07-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='owner',
            new_name='author',
        ),
    ]
