# Generated by Django 5.0.7 on 2024-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_owner_invoice_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='invoice.item'),
        ),
    ]
