# Generated by Django 5.0.7 on 2024-07-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='invoices', to='invoice.item'),
        ),
    ]
