# Generated by Django 5.0.7 on 2024-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_remove_invoice_items_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='identifier',
            field=models.CharField(auto_created=True, default=None, max_length=6),
            preserve_default=False,
        ),
    ]
