# Generated by Django 5.0.7 on 2024-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='identifier',
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.CharField(auto_created=True, default=None, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
