# Generated by Django 5.0.7 on 2024-12-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_item_owner_invoice_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='clientAddress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='invoice.address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='senderAddress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='invoice.address'),
        ),
    ]
