# Generated by Django 5.0.7 on 2024-12-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_remove_invoice_items_item_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
    ]
