# Generated by Django 5.0.7 on 2024-07-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
