# Generated by Django 5.0.7 on 2024-12-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
